/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MyCalculator;

public class Grundrechnungsarten {
	
    public Integer addTwoNumbers(Integer num1, Integer num2) {
    	
        return num1 + num2;
    }
    
    public Integer multiplyTwoNumbers (Integer num1, Integer num2) {
    	
    	System.out.println("Explain what to do");
    	
    	return num1 * num2;
    	
    	
    }
}
