/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MyCalculator;

public class Grundrechnungsarten {
	
    public Integer addTwoNumbers(Integer num1, Integer num2) {
    	
        return num1 + num2;
    }
    
    public Integer multiplyTwoNumbers (Integer num1, Integer num2) {
    	
    	return num1 * num2;
    	
    	
    }
    
    public Integer subtractTwoNumbers (Integer num1, Integer num2) {
    	return num1 - num2;
    }
    
    public Double divideTwoNumbers (Integer num1, Integer num2) {
    	
    	try {
    		
    		return (double) (num1 / num2);
    	}
    	catch (ArithmeticException e) {
            System.out.println ("Division durch Null nicht möglich: " + e);
         }
		return null;
    }
}
