/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MyCalculator;

public class Grundrechnungsarten {
	
    public Integer addTwoNumbers(Integer num1, Integer num2) {
    	
        return num1 + num2;
    }
}
