/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MyCalculator;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Grundrechnungsarten classUnderTest = new Grundrechnungsarten();
        assertEquals((Integer) 6, classUnderTest.addTwoNumbers(4, 2));
        assertEquals((Integer) 0, classUnderTest.addTwoNumbers(-1, 1));
        assertEquals((Integer) 4, classUnderTest.addTwoNumbers(-4, 8));
        
        
        
    }
}
